#!/bin/bash

echo "🛠️  Cloudinary Upload Preset Setup Guide"
echo ""
echo "You need to create an upload preset in your Cloudinary dashboard:"
echo ""
echo "1. 🌐 Go to: https://console.cloudinary.com/"
echo "2. 🔧 Navigate to: Settings → Upload"
echo "3. ➕ Click: 'Add upload preset'"
echo "4. 📝 Fill in the details:"
echo "   - Preset name: luna_gems_products"
echo "   - Signing Mode: Unsigned"
echo "   - Folder: luna-gems/products (optional but recommended)"
echo "   - Use filename: false"
echo "   - Unique filename: true"
echo ""
echo "5. 🖼️  Optional transformations:"
echo "   - Max width: 1200"
echo "   - Max height: 1200"
echo "   - Quality: auto"
echo "   - Format: auto"
echo ""
echo "6. 💾 Click 'Save'"
echo ""
echo "✅ Your current configuration:"
echo "   Cloud Name: teravexsoftwares"
echo "   Upload Preset: luna_gems_products"
echo ""
echo "🔗 Direct link to settings: https://console.cloudinary.com/settings/upload"
