#!/bin/bash

echo "🔐 Admin Password Setup for Luna Gems"
echo ""
echo "Current Setup:"
echo "✅ Admin authentication is now enabled"
echo "✅ Password is secured with server-side validation"
echo "✅ Session expires after 24 hours"
echo ""
echo "🔑 Current Password: LunaGems2024!"
echo ""
echo "📝 To Change Password:"
echo "1. Update ADMIN_PASSWORD in your .env.local file"
echo "2. Restart your development server"
echo ""
echo "🏭 For Production:"
echo "1. Generate a password hash:"
echo "   node -e \"console.log(require('bcryptjs').hashSync('YOUR_PASSWORD', 10))\""
echo "2. Set ADMIN_PASSWORD_HASH environment variable"
echo "3. Remove ADMIN_PASSWORD from production environment"
echo ""
echo "🛡️ Security Features:"
echo "• Password validation via secure API route"
echo "• Session management with expiration"
echo "• Automatic logout after 24 hours"
echo "• Secure password hashing for production"
echo ""
echo "🚀 Access Admin Panel:"
echo "   http://localhost:9002/admin"
