#!/bin/bash

echo "🌩️  Setting up Cloudinary Image Upload for Luna Gems Admin"
echo ""
echo "Follow these steps to configure Cloudinary:"
echo ""
echo "1. 📝 Create a Cloudinary Account (if you don't have one):"
echo "   - Go to https://cloudinary.com"
echo "   - Sign up for a free account"
echo ""
echo "2. 🔑 Get your Cloudinary credentials:"
echo "   - Go to your Cloudinary Dashboard"
echo "   - Copy your Cloud Name, API Key, and API Secret"
echo ""
echo "3. 📂 Create Upload Preset:"
echo "   - In Cloudinary Dashboard, go to Settings > Upload"
echo "   - Click 'Add upload preset'"
echo "   - Set Preset name: luna_gems_products"
echo "   - Set Signing Mode: Unsigned"
echo "   - Set Folder: luna-gems/products (optional)"
echo "   - Set Transformation: Limit dimensions to 1200x1200"
echo "   - Save the preset"
echo ""
echo "4. 🔧 Update Environment Variables:"
echo "   Add these to your .env.local file:"
echo ""
echo "   NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=your_cloud_name_here"
echo "   CLOUDINARY_API_KEY=your_api_key_here"
echo "   CLOUDINARY_API_SECRET=your_api_secret_here"
echo "   NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=luna_gems_products"
echo ""
echo "5. 🚀 Restart your development server:"
echo "   npm run dev"
echo ""
echo "✨ Features you'll get:"
echo "   • Drag & drop image upload"
echo "   • Automatic image optimization"
echo "   • Multiple image formats support"
echo "   • CDN delivery for fast loading"
echo "   • Image transformations"
echo ""
echo "📁 Example .env.local configuration in: .env.example.cloudinary"
