#!/bin/bash

echo "🛠️  Setting up Products Table for Luna Gems Admin Dashboard"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Open your Supabase dashboard"
echo "2. Go to the SQL Editor"
echo "3. Copy and paste the contents of docs/products-table-setup.sql"
echo "4. Run the SQL script"
echo ""
echo "The script will:"
echo "   ✅ Create the products table"
echo "   ✅ Set up Row Level Security (RLS)"
echo "   ✅ Create necessary policies"
echo "   ✅ Add sample products"
echo "   ✅ Create indexes for performance"
echo ""
echo "After running the SQL script, your admin dashboard will be able to:"
echo "   • Add new products to the database"
echo "   • Edit existing products"
echo "   • Delete products"
echo "   • Toggle product stock status"
echo "   • View all products from the database"
echo ""
echo "📁 SQL file location: docs/products-table-setup.sql"
